export const REACT_APP_GOOGLE_API_KEY =
  "AIzaSyDocHajIQ2Mdx-nyvd0ymr4B29rJW-IdT8";

export const REACT_APP_GOOGLE_ACCESS_TOKEN =
  "ya29.a0Aa4xrXPAw0QV76s2NWCkNMdCOJFMjcTdRFPMAcXFQ-gcfxoM-aFaWoaD-mG1ct0gzR0msHlvWvq0eFAeTvhJGHzzSw-fRd_Z7Vag_Glm4iYnNXVas8T-tntO1G-iToG58M0J1AaUSM7NBuoFyz6WYruI6MSwaCgYKATASARASFQEjDvL9UbW09lFunRF4fqG5k647SQ0163";

export const REACT_APP_CALENDAR_ID = "peter.benc@vacuumlabs.com";
